# Generated by Django 2.2.7 on 2019-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
